name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
  tags:
    - 'v*'

jobs:
    build:
        if: contains(github.event.head_commit.message, '[build]')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo "Build triggered due to commit message [build]"